version: '3'
services:
  mongodb:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pic
      - MONGO_INITDB_ROOT_PASSWORD=image
      - MONGO_INITDB_DATABASE=catalog
    restart: on-failure
    ports:
      - 27017:27017
    #volumes:
    #  - ./mongodb:/data/db